import { mkdirSync, readFileSync, writeFileSync, copyFileSync } from 'node:fs';
import { extraProjects } from '../extra-scenarios.mjs';
import { roadmapProjects } from '../roadmap-scenarios.mjs';
import { expansionProjects } from '../business-expansion.mjs';

const root = new URL('./', import.meta.url);
const projects = [...extraProjects, ...roadmapProjects, ...expansionProjects];
const headings = readFileSync(new URL('../../41 Templates/sop-master-template.md', import.meta.url), 'utf8').match(/^## \d+\. .+$/gm);
const domain = {
 'PM-01': ['maintenance_request', 'description text NOT NULL CHECK (length(btrim(description)) > 0),\n  access_approved boolean NOT NULL DEFAULT false', 'Tenant issue → emergency or routine triage → operator/access/vendor review', 'Compare emergency escalation, missing access and approved access. Dispatch stays disabled.'],
 'EA-01': ['commitment', 'owner_name text NOT NULL CHECK (length(btrim(owner_name)) > 0),\n  commitment_text text NOT NULL CHECK (length(btrim(commitment_text)) > 0),\n  authorized boolean NOT NULL DEFAULT false,\n  confirmed boolean NOT NULL DEFAULT false', 'Authorized commitment → identity reconciliation → owner review', 'Show duplicate collapse, unauthorized exclusion and conflicting identity rejection.'],
 'CON-01': ['change_request', 'requester text NOT NULL,\n  amount_cents bigint NOT NULL CHECK (amount_cents >= 0),\n  version integer NOT NULL CHECK (version > 0),\n  certificate_expiry date NOT NULL', 'Change amount and version → independent approval checks → release review', 'Change the amount or requester to invalidate approvals; inspect the hash-linked evidence.'],
 'MED-01': ['referral', 'payer_code text NOT NULL,\n  storage_consent boolean NOT NULL DEFAULT false,\n  documents jsonb NOT NULL CHECK (jsonb_typeof(documents) = \'array\')', 'Referral → fictional payer checklist → administration review', 'Compare complete documents, missing order, unknown payer and absent consent.'],
 'LEGAL-01': ['matter_intake', 'parties jsonb NOT NULL CHECK (jsonb_typeof(parties) = \'array\'),\n  adverse_entities jsonb NOT NULL CHECK (jsonb_typeof(adverse_entities) = \'array\')', 'Party names → normalized exact/ambiguous matching → attorney clearance', 'Compare exact, ambiguous and unmatched names; no route creates a matter.'],
 'INS-01': ['claim_intake', 'loss_date date NOT NULL,\n  policy_start date NOT NULL,\n  policy_end date NOT NULL CHECK (policy_end >= policy_start),\n  documents jsonb NOT NULL CHECK (jsonb_typeof(documents) = \'array\')', 'Loss intake → dates and evidence checks → adjuster review', 'Inspect missing evidence, out-of-window loss and duplicate signals; coverage remains undecided.'],
 'INV-01': ['stock_snapshot', 'sku text NOT NULL,\n  on_hand integer NOT NULL CHECK (on_hand >= 0),\n  reserved integer NOT NULL CHECK (reserved >= 0 AND reserved <= on_hand),\n  target integer NOT NULL CHECK (target >= 0),\n  pack_size integer NOT NULL CHECK (pack_size > 0),\n  stock_age_hours integer NOT NULL CHECK (stock_age_hours >= 0)', 'Stock snapshot → reservations and pack rounding → buyer review', 'Show 48 proposed units, stale-stock refresh and no-order paths; no purchase is sent.'],
 'CRM-01': ['account_handoff', 'account_id text NOT NULL,\n  owner_name text NOT NULL,\n  email text NOT NULL,\n  incoming_version integer NOT NULL CHECK (incoming_version >= 0),\n  current_version integer NOT NULL CHECK (current_version >= 0),\n  consent boolean NOT NULL DEFAULT false', 'Account event → consent/version/minimization → sync review', 'Show canonical email, stale version and no-consent routes; no hosted CRM write occurs.'],
 'AGT-01': ['tool_proposal', 'ticket_id text NOT NULL,\n  tool_name text NOT NULL,\n  estimated_cents integer NOT NULL CHECK (estimated_cents >= 0),\n  budget_cents integer NOT NULL CHECK (budget_cents >= 0),\n  grounded boolean NOT NULL DEFAULT false', 'Proposed tool → allowlist, budget and grounding signal → draft review', 'Compare allowed draft, refund tool and excess budget. The grounding boolean is supplied input, not an LLM evaluation.'],
 'OPS-01': ['recovery_event', 'attempt integer NOT NULL CHECK (attempt >= 0),\n  http_status integer NOT NULL CHECK (http_status >= 0),\n  retry_after_seconds integer NOT NULL CHECK (retry_after_seconds >= 0),\n  confirmed boolean NOT NULL DEFAULT false,\n  uncertain boolean NOT NULL DEFAULT false', 'Handoff failure → certainty and retryability checks → recovery plan', 'Compare rate limit delay, uncertain write reconciliation and completed replay; retries are proposed, not scheduled.'],
};
const footer = '\n---\n*Part of the Enterprise Automation Portfolio. See [project build index](../README.md).*\n';
for (const p of projects) {
 const id = p.id, dir = new URL(`${id}/`, root), build = new URL('build/', dir);
 mkdirSync(build, { recursive: true });
 const [entity, fields, flow, cue] = domain[id];
 const schema = id.toLowerCase().replace('-', '_');
 const sql = `-- Proposed PostgreSQL persistence model; the local demo currently uses SQLite.\n-- Apply once to a fresh disposable database. No DROP statements or runtime wiring.\nBEGIN;\nCREATE SCHEMA ${schema};\nCREATE TABLE ${schema}.${entity} (\n  id text PRIMARY KEY CHECK (length(btrim(id)) > 0),\n  ${fields},\n  created_at timestamptz NOT NULL DEFAULT CURRENT_TIMESTAMP\n);\nCREATE TABLE ${schema}.decision_event (\n  id bigint GENERATED ALWAYS AS IDENTITY PRIMARY KEY,\n  subject_id text NOT NULL REFERENCES ${schema}.${entity}(id),\n  event_key text NOT NULL UNIQUE CHECK (length(btrim(event_key)) > 0),\n  source_hash text NOT NULL CHECK (source_hash ~ '^[0-9a-f]{64}$'),\n  queue text NOT NULL CHECK (length(btrim(queue)) > 0),\n  output jsonb NOT NULL CHECK (jsonb_typeof(output) = 'object'),\n  recorded_at timestamptz NOT NULL DEFAULT CURRENT_TIMESTAMP\n);\nCREATE INDEX ON ${schema}.decision_event (subject_id, recorded_at);\nCOMMIT;\n`;
 writeFileSync(new URL('schema.sql', build), sql);
 copyFileSync(new URL(`../workflows/${id}.json`, root), new URL('n8n-workflow.json', build));
 let js;
 if (id === 'PM-01') js = `import assert from 'node:assert/strict';\nimport { maintenance } from '../../../extra-scenarios.mjs';\nconst cases = [\n ['Emergency', {description:'Gas leak near boiler',accessApproved:false}, 'human_emergency_operator'],\n ['Access missing', {description:'Broken cupboard',accessApproved:false}, 'access_confirmation'],\n ['Access approved', {description:'Broken cupboard',accessApproved:true}, 'vendor_review']\n].map(([name,input,queue]) => { const output=maintenance(input); assert.equal(output.queue,queue); assert.equal(output.dispatchAllowed,false); return {name,passed:true,output}; });\nassert.throws(()=>maintenance({description:''}),/Description required/);\ncases.push({name:'Empty description rejected',passed:true});\nconsole.log(JSON.stringify({projectId:'PM-01',evaluation:{passed:cases.length,total:cases.length,cases}},null,2));\n`;
 else if (id === 'EA-01') js = `import assert from 'node:assert/strict';\nimport { commitments, extraProjects } from '../../../extra-scenarios.mjs';\nconst input=structuredClone(extraProjects.find(p=>p.id==='EA-01').fixture);\nconst output=commitments(input);\nassert.equal(output.retainedCount,1); assert.equal(output.items[0].status,'needs_owner_review'); assert.equal(output.externalActions,0);\nconst first=input.items[0];\nassert.throws(()=>commitments({items:[first,{...first,owner:'Conflicting owner'}]}),/Conflicting/);\nassert.throws(()=>commitments({items:[]}),/1–100/);\nassert.equal(commitments({items:[{...first,confirmed:true}]}).items[0].status,'confirmed');\nconst cases=['Dedupe and authorization','Conflicting identity rejection','Empty list rejection','Confirmed status'].map(name=>({name,passed:true}));\nconsole.log(JSON.stringify({projectId:'EA-01',output,evaluation:{passed:cases.length,total:cases.length,cases}},null,2));\n`;
 else js = `import { ${id.startsWith('CON')||id.startsWith('MED')||id.startsWith('LEGAL')||id.startsWith('INS')?'evaluateRoadmap':'evaluateExpansion'} as evaluate } from '../../../${id.startsWith('CON')||id.startsWith('MED')||id.startsWith('LEGAL')||id.startsWith('INS')?'roadmap-scenarios':'business-expansion'}.mjs';\nconsole.log(JSON.stringify(evaluate('${id}'),null,2));\n`;
 writeFileSync(new URL('demo.js', build), js);
 const readme = `# ${p.title}\n\nStatus: **Populated — bounded local build; hosted integration and PostgreSQL execution pending.**\n\n${p.demo}\n\n**Video Walkthrough:** _Pending recording — see script in this SOP's project folder._\n**Real Build Artifacts:** [Runbook and build files →](build/README.md)\n\n## Business flow\n\n${flow}.\n\n## Review materials\n\n- [44-section SOP](SOP.md)\n- [Recording script](walkthrough-script.md)\n- [Build runbook](build/README.md)\n\n${footer}`;
 writeFileSync(new URL('README.md', dir), readme);
 writeFileSync(new URL('README.md', build), `# ${id} build runbook\n\nStatus: **Populated — local script and copied workflow available; PostgreSQL execution pending.**\n\n## Files\n\n- \`demo.js\`: imports the existing business implementation and executes assertions against synthetic fixtures.\n- \`n8n-workflow.json\`: exact copy of the local five-node orchestration export; calls the local API and simulated GHL contact service.\n- \`schema.sql\`: proposed two-table PostgreSQL persistence model, with identity, foreign key, event deduplication and source-hash constraints. It is not wired to the current SQLite runtime.\n\n## Run from the repository root\n\n\`node demo-lab/project-builds/${id}/build/demo.js\`\n\nFor the full local demonstration, run \`npm ci --prefix demo-lab\`, then \`node demo-lab/server.mjs\`. Open http://127.0.0.1:5680, select ${id} and run the demo. The dashboard imports and executes the local workflow with its bundled n8n version and records actual results. Importing this workflow elsewhere requires the API to remain reachable at the exported loopback address; a remote n8n server cannot reach your workstation through its own localhost.\n\n## PostgreSQL deployment\n\nIn a fresh disposable PostgreSQL database, run \`psql -X -v ON_ERROR_STOP=1 -d portfolio_demo -f demo-lab/project-builds/${id}/build/schema.sql\`. Connection settings are standard PGHOST, PGPORT, PGUSER, PGPASSWORD and PGDATABASE, supplied privately by the operator. This DDL is one-time setup, not a repeatable migration. SQL has a structural check only until a PostgreSQL engine execution is recorded.\n\n## Hosted integration boundary\n\nNo external credentials are needed for this local run. A hosted deployment needs authenticated source intake, a dedicated GHL location and its actual provider credentials, persistence adapters, role enforcement and verified recovery. There is no hosted GHL writer in these files. The local demonstration token is not a provider credential.\n\n## Expected evidence\n\n${cue} Keep actual failure output when an assertion fails. Do not replace it with a success claim. See [SOP](../SOP.md) and [recording script](../walkthrough-script.md).\n\n---\n*Part of the Enterprise Automation Portfolio. See [project overview](../README.md).*\n`.replaceAll('\`','`'));
 const content = [
  p.demo, `${flow}. Manual review remains explicit.`, 'Make administrative decisions reproducible and inspectable; demonstrate the decision boundary before hosted deployment.',
  cue, 'Validate synthetic input, calculate the decision, retain review requirements and return machine-readable evidence.',
  'Node.js 24+, repository source modules, n8n dependencies for the dashboard. PostgreSQL is a separate proposed persistence target.',
  '[Shared runtime](../../server.mjs), [source modules](../../catalog.mjs) and [build runbook](build/README.md).',
  'JavaScript business rules, n8n orchestration, local HTTP endpoints and SQLite evidence store. GHL is simulated; PostgreSQL is proposed.',
  'Presenter operates the local demo; a domain reviewer evaluates the decision; an integration owner handles hosted acceptance.',
  'The presenter distinguishes source assertions from live provider evidence. The reviewer owns approvals and business outcomes.',
  `\`\`\`mermaid\nflowchart LR\n  A[Synthetic input] --> B[Validate business fields]\n  B --> C[Evaluate rules]\n  C --> D[Human review output]\n  D --> E[Local contact handoff]\n\`\`\`\n\n${flow}.`,
  'Run the standalone script; inspect each assertion; start the lab; run the selected n8n demo; inspect node results, business output and saved evidence.',
  cue, `Source is [${p.source.split('/').pop()}](../../${p.source.split('/').pop()}). The build runner imports it without duplicating business logic.`,
  'Explicit manual script execution or dashboard run. No background schedule, public webhook or autonomous external action is installed.',
  'The imported function validates its typed fields; evaluation fixtures cover accepted and rejected cases. PostgreSQL constraints protect the proposed storage shape, not every domain rule.',
  'Assertion failures exit nonzero. The dashboard records failed runs. Preserve the failing input and source revision for diagnosis.',
  id==='OPS-01'?'The business function calculates retry delay and attempt limits; no retry worker executes the plan. Uncertain writes require reconciliation.':'No business-action retry worker exists. Review uncertain external outcomes before adding any future retry.',
  'Stop at human review and retain the failed evidence. The standalone script can isolate business logic from n8n/API issues.',
  'No administrative bypass is implemented. Change reviewed source or synthetic fixtures explicitly; never edit saved evidence to convert a failure into a pass.',
  cue, 'No messages are sent. Future notifications require a recipient policy and provider acceptance tests.',
  'The current runtime records run IDs, source hashes, node evidence and output in SQLite. The proposed SQL decision_event table is not yet a runtime audit trail.',
  'Local synthetic inputs and loopback API reduce exposure. Production deployment requires authenticated intake, secret storage and least-privilege provider access.',
  'No production role-based access control is claimed. Human review queues describe responsibility; they do not authenticate a reviewer.',
  'No legal, clinical, insurance or regulatory certification is asserted. Domain professionals must approve real operating rules.',
  'Report observed local execution duration and case counts separately from throughput, availability and production latency, which remain unmeasured.',
  p.presenter?.[3] || 'Review turnaround, exception rate and operator acceptance; no measured client baseline is available.',
  'Run [demo.js](build/demo.js); parse the workflow JSON; confirm its copy matches the generated local workflow; structurally inspect SQL. Engine execution and hosted acceptance remain separate gates.',
  'Follow [build runbook](build/README.md). Complete PostgreSQL execution, adapter tests and dedicated provider test-location acceptance before hosted release.',
  'When source rules change, rerun assertions and regenerate local workflows before refreshing copied build artifacts. Review fictional rule assumptions with domain owners.',
  '| Version | Date | Change |\n|---|---|---|\n| 1.0 | 2026-09-10 | Added bounded build artifacts, proposed SQL and operating procedure. |',
  'Wire durable persistence; add authenticated intake and reviewer actions; prove provider recovery; record the walkthrough; collect measured outcomes.',
  `\`\`\`mermaid\nerDiagram\n  ${entity} ||--o{ decision_event : receives\n  ${entity} {\n    text id PK\n    timestamptz created_at\n  }\n  decision_event {\n    bigint id PK\n    text subject_id FK\n    text event_key UK\n    text source_hash\n    text queue\n    jsonb output\n    timestamptz recorded_at\n  }\n\`\`\`\n\nDomain columns are specified in [schema.sql](build/schema.sql). Diagram shows key relationships; SQL is authoritative for additional fields and constraints.`,
  'Connection refused: start the local server on port 5680. Missing module: run from the intact repository with Node 24+. Assertion failure: inspect the named case before changing expectations.',
  'Keep the failed run and correct configuration or source. Rerun synthetic inputs; compare saved evidence. Hosted uncertainty must be reconciled at the provider before retry.',
  'Does this execute hosted GHL? No. Does proposed SQL replace SQLite? No. Does the local n8n workflow execute source code through HTTP? Yes, when the local server is running.',
  'Workflow artifact is copied exactly from demo-lab/workflows. Local contact deduplication does not establish business-event idempotency. SQL event keys need a future writer to enforce them operationally.',
  'The business scenario is bounded and demonstrable. No specific client delivery history, production scale or financial result is inferred.',
  'Unmeasured. Collect manual review time and comparable assisted review time before making a savings claim.',
  'No ROI value is claimed. Calculate benefit from observed volume and net time saved, subtracting infrastructure and review costs.',
  'Primary risks: treating a review proposal as an executed action, stale domain rules, conflating synthetic fixtures with production evidence and treating proposed SQL as deployed persistence.',
  'Expose decisions, exceptions and evidence separately so a reviewer can inspect the implementation boundary.',
  '[Portfolio verification](../../VERIFICATION.md), [build status](../../BUILD-ARTIFACT-STATUS.md) and [project overview](README.md).',
 ];
 writeFileSync(new URL('SOP.md', dir), `# ${p.title}\n\nStatus: **Populated — bounded local implementation; integration acceptance pending.**\nVersion: 1.0 · Owner: portfolio maintainer\n\n**Video Walkthrough:** _Pending recording — see script in this SOP's project folder._\n**Real Build Artifacts:** [Runbook and build files →](build/README.md)\n\n${headings.map((h,i)=>h+'\n\n'+content[i]).join('\n\n')}${footer}`.replaceAll('\`','`'));
 writeFileSync(new URL('walkthrough-script.md', dir), `# ${id} walkthrough script\n\nStatus: **Populated — recording pending.**\n\n**Video Walkthrough:** _Pending recording — see script in this SOP's project folder._\n\n## Narration and screen cues (3–5 minutes)\n\n1. Open ${id} in the local dashboard. Say: “${p.demo} This is a local synthetic build with explicit human review.”\n2. Show the workflow graph and trace: ${flow}. Explain that the five-node n8n wrapper executes source over the local API and hands a synthetic contact to the local GHL simulator.\n3. Run the demo and inspect actual saved node evidence. ${cue}\n4. Open source and run \`node demo-lab/project-builds/${id}/build/demo.js\`. Explain one accepted case and one rejected or review case.\n5. Show proposed schema relationships. Say: “This PostgreSQL model is supplied as an integration artifact; the running lab uses SQLite. I am not presenting this as a deployed PostgreSQL integration.”\n6. Close with the remaining delivery gates: real authenticated intake, hosted provider acceptance, a domain owner’s approval and measured business results.\n\nKeep this recording pending until the video actually exists and its link is added to the central index.${footer}`.replaceAll('\`','`'));
}
writeFileSync(new URL('README.md', root), '# Bounded project builds\n\nStatus: **Populated — ten artifact sets; integration verification remains explicit.**\n\n'+projects.map(p=>`- [${p.title}](${p.id}/README.md)`).join('\n')+'\n\nRegenerate copies after canonical workflow changes with `node demo-lab/project-builds/generate.mjs`. Generator imports existing catalog entries and writes only this folder.\n\n---\n*Part of the Enterprise Automation Portfolio. See [local lab](../README.md).*\n');
