import test from 'node:test';
import assert from 'node:assert/strict';
import { readFileSync } from 'node:fs';
import { JSDOM } from 'jsdom';
import { createLabServer,openStore } from './server.mjs';
import { projects } from './catalog.mjs';

test('dashboard renders every project, architecture, measurements and failed-run presentation',async t=>{
  const db=openStore(':memory:');
  db.prepare('INSERT INTO runs VALUES(?,?,?,?,?)').run('ui-failure','ECOM-01','failed',JSON.stringify({error:'Deliberate test fixture failure'}),'2026-09-09T00:00:00Z');
  db.prepare('INSERT INTO runs VALUES(?,?,?,?,?)').run('ui-success','ECOM-01','passed',JSON.stringify({engineDurationMs:200,wallDurationMs:500,nodeEvidence:[{name:'Business source',status:'success',durationMs:0},{name:'Contact',status:'success',durationMs:150}]}),'2026-09-08T00:00:00Z');
  const server=createLabServer(db);
  await new Promise(resolve=>server.listen(0,'127.0.0.1',resolve));
  const base=`http://127.0.0.1:${server.address().port}`;
  const dom=new JSDOM(readFileSync(new URL('./index.html',import.meta.url),'utf8'),{url:base,runScripts:'outside-only'});
  const w=dom.window;
  w.fetch=(path,options)=>fetch(base+path,options);
  // jsdom does not implement native dialog presentation; exercise its contents here.
  w.HTMLDialogElement.prototype.showModal=function(){this.open=true};
  w.HTMLDialogElement.prototype.close=function(){this.open=false};
  t.after(async()=>{w.close();await new Promise(resolve=>server.close(resolve));db.close()});
  const waitFor=async predicate=>{for(let i=0;i<300;i++){if(predicate())return;await new Promise(resolve=>setTimeout(resolve,10))}throw new Error('Dashboard did not reach expected state: '+w.document.getElementById('status').textContent)};
  w.eval(readFileSync(new URL('./studio.js',import.meta.url),'utf8'));
  await waitFor(()=>w.document.querySelectorAll('[data-node]').length===5);
  const el=id=>w.document.getElementById(id);
  assert.match(el('projectId').textContent,/^ECOM-01/);
  assert.equal(el('portfolioGallery').hidden,false);
  assert.equal(el('labShell').hidden,true);
  assert.ok(el('galleryContent').querySelector('a[href="/engineering#ENG-05"]'));
  el('startAutomationRoute').click();
  assert.equal(el('labShell').hidden,false);
  assert.match(el('projectId').textContent,/ECOM-01/);
  el('portfolioHome').click();
  assert.equal(el('galleryContent').querySelectorAll('[data-open-project]').length,6);
  assert.equal(el('galleryContent').querySelectorAll('meter').length,3);
  const selectGallery=label=>[...el('galleryContent').querySelectorAll('[data-gallery-filter]')].find(b=>b.textContent===label).click();
  selectGallery('All projects');
  assert.equal(el('galleryContent').querySelectorAll('[data-open-project]').length,projects.length);
  selectGallery('AI and knowledge');
  assert.ok(el('galleryContent').querySelector('[data-open-project="AGT-01"]'));
  assert.ok(!el('galleryContent').querySelector('[data-open-project="ECOM-01"]'));
  selectGallery('Selected');
  el('galleryContent').querySelector('[data-open-project="ECOM-01"]').click();
  assert.equal(el('portfolioGallery').hidden,true);
  assert.equal(el('labShell').hidden,false);
  el('portfolioHome').click();
  assert.equal(el('portfolioGallery').hidden,false);
  el('openLab').click();
  assert.equal(el('labShell').hidden,false);

  assert.ok(el('overviewWorkflow').querySelector('svg'));
  assert.match(el('projectAnalytics').textContent,/2 saved runs/);
  assert.match(el('projectAnalytics').textContent,/200 ms/);
  assert.match(el('projectAnalytics').textContent,/n=1/);
  assert.match(el('projectAnalytics').textContent,/No recorded measurements available/);
  assert.match(el('hiringEvidence').textContent,/What engineering judgment/);
  assert.match(el('runExplanation').textContent,/ui-failure: failed/);
  assert.match(el('runExplanation').textContent,/Deliberate test fixture failure/);
  const older=el('history').querySelector('[data-run="ui-success"]');
  older.click();
  assert.match(el('projectAnalytics').textContent,/Business source/);
  assert.match(el('projectAnalytics').textContent,/0 ms/);
  assert.equal(w.eval('timingValue(null)'),false);
  assert.equal(w.eval('timingValue(-1)'),false);
  assert.equal(w.eval('timingValue(0)'),true);
  el('history').querySelector('[data-run="ui-failure"]').click();
  el('inspectWorkflow').click();
  assert.match(el('graphScope').textContent,/original source export/);
  assert.ok(el('workflowCanvas').querySelectorAll('path').length>4);
  el('graphDemo').click();
  el('graphZoomIn').click();
  assert.equal(el('graphZoom').textContent,'120%');
  el('graphZoomOut').click();
  assert.equal(el('graphZoom').textContent,'100%');
  assert.equal(el('projects').querySelectorAll('button').length,projects.length);
  el('present').click();
  while(!el('next').disabled)el('next').click();
  assert.match(el('slide').textContent,/This run needs attention/);
  el('closeDeck').click();
  for(const p of projects){
    el('projects').querySelector(`[data-id="${p.id}"]`).click();
    await waitFor(()=>w.document.querySelectorAll('[data-node]').length===5);
    assert.ok(!el('story').textContent.includes('undefined'),p.id);
    assert.ok(el('beforeMinutes'),p.id);
    assert.match(el('description').textContent,/What it does:/,p.id);
    assert.match(el('specialistExample').textContent,/AI automation specialist in practice/,p.id);
    assert.ok(el('specialistExample').querySelector('p').textContent.length>200,p.id);
    assert.ok(!el('specialistExample').textContent.includes('undefined'),p.id);
    assert.match(el('description').textContent,/How it works:/,p.id);
    assert.ok(!el('description').textContent.includes('undefined'),p.id);
    assert.equal(el('story').querySelectorAll('.io-flow > div').length,3,p.id);
    assert.match(el('story').textContent,/What happens next/,p.id);
    assert.match(el('runExplanation').textContent,/Business purpose/,p.id);
    assert.ok(el('projectAnalytics').querySelector('svg'),p.id);
    assert.ok(el('hiringEvidence').querySelector('table'),p.id);
    w.document.querySelector('[data-node="4"]').dispatchEvent(new w.Event('click'));
    assert.match(el('archDetail').textContent,/Execution complete/);
    el('present').click();
    const agenda=el('deckAgenda');
    assert.equal(agenda.options.length,10,p.id);
    for(let slide=0;slide<10;slide++){
      agenda.value=String(slide);agenda.dispatchEvent(new w.Event('change'));
      if(slide===6)await waitFor(()=>!!el('slide').querySelector('.deck-source pre'));
      if(slide===1){
        assert.match(el('slide').textContent,/The situation/);
        assert.match(el('slide').textContent,/What the system checks/);
        assert.match(el('slide').textContent,/How the person starts/);
        assert.match(el('slide').textContent,/What the person receives and does next/);
      }
      assert.ok(el('slide').querySelector('.deck-explanation'),p.id);
      assert.ok(el('slide').querySelector('.deck-support').textContent.trim().length>40,p.id);
    }
    agenda.value=[...agenda.options].find(o=>o.textContent.includes('Files behind the system')).value;
    agenda.dispatchEvent(new w.Event('change'));
    const source=el('slide').querySelector('[data-deck-source="source"]');
    assert.ok(source,p.id);source.click();
    await waitFor(()=>!!el('slide').querySelector('.deck-source pre'));
    assert.ok(el('slide').querySelector('.deck-source pre').textContent.startsWith('   1'),p.id);
    const search=el('slide').querySelector('.deck-source input');search.value='unlikely-search-token-999';search.dispatchEvent(new w.Event('input'));
    assert.equal(el('slide').querySelector('.deck-source [role=status]').textContent,'No match');
    el('closeDeck').click();
  }
  el('beforeMinutes').value='12';el('afterMinutes').value='7';el('monthlyItems').value='120';
  el('monthlyItems').dispatchEvent(new w.Event('input'));
  assert.match(el('measurementResult').textContent,/10.00 hours saved/);
  el('afterMinutes').value='17';el('afterMinutes').dispatchEvent(new w.Event('input'));
  assert.match(el('measurementResult').textContent,/10.00 hours added/);
  el('monthlyItems').value='1.5';el('monthlyItems').dispatchEvent(new w.Event('input'));
  assert.match(el('measurementResult').textContent,/whole-number/);
  el('collection').value='new';el('collection').dispatchEvent(new w.Event('change'));
  assert.equal(el('projects').querySelectorAll('button').length,4);
  el('collection').value='all';el('collection').dispatchEvent(new w.Event('change'));
  el('search').value='nonexistent-project';el('search').dispatchEvent(new w.Event('input'));
  assert.match(el('projects').textContent,/No matching projects/);
});
