import { test } from 'node:test';
import assert from 'node:assert/strict';
import { supportDesk, routingLab, mergePreview, journey, usageLedger, scheduleBoard, instant } from './flagship-decisions.mjs';
import { flagshipFixtures } from './flagship-fixtures.mjs';
import { reconstructionChallenge } from './reconstruction.mjs';
const fixture = id => structuredClone(flagshipFixtures[id]);
test('empty evaluation, conflicting simultaneous grants and prematurely posted credits fail closed', () => { assert.throws(() => routingLab({ ...fixture('F04'), cases: [] }), /At least/); const consent = fixture('F09'); consent.events = consent.events.slice(0, 1); consent.events.push({ ...consent.events[0], id: 'second-grant', expiresAt: '2026-12-01T12:00:00.000Z' }); assert.equal(journey(consent).reason, 'conflicting_grants'); const ledger = fixture('F10'); ledger.events[0].postedAt = '2026-09-20T12:00:00.000Z'; ledger.events[1].postedAt = ledger.events[1].occurredAt; assert.throws(() => usageLedger(ledger), /earlier posted/); });
test('support cites exact approved excerpts, isolates tenants and excludes flagged instruction text', () => { const x = fixture('F03'); const good = supportDesk(x); assert.equal(good.citations[0], 'returns'); assert.equal(good.answer, 'Unopened products may be returned within 30 days.'); for (const query of ['private', 'refund', 'warranty', 'returns shipping']) {
    const r = supportDesk({ ...x, query });
    assert.equal(r.status, 'abstain');
    assert.equal(r.externalActions, 0);
} x.documents[0].approved = false; assert.equal(supportDesk(x).status, 'abstain'); });
test('routing escalates verification failures, accounts for both attempts and keeps labels out of routing', () => { const x = fixture('F04'); const r = routingLab(x); assert.equal(r.passed, 3); assert.equal(r.spentScenarioUnits, 13); assert.deepEqual(r.trials.map(t => t.route), ['cheap', 'escalation', 'escalation']); const relabeled = fixture('F04'); relabeled.cases[0].expectedCitation = 'shipping'; assert.equal(routingLab(relabeled).trials[0].route, 'cheap'); assert.equal(routingLab(relabeled).passed, 2); x.budgetUnits = 2; const capped = routingLab(x); assert.equal(capped.spentScenarioUnits, 2); assert.equal(capped.trials[1].route, 'budget_stop'); x.trainingIds = ['eval-return']; assert.throws(() => routingLab(x), /overlaps/); });
test('merge preview fills only empty safe fields and reverses the exact local simulation', () => { const x = fixture('F07'), original = JSON.stringify(x); const r = mergePreview(x); assert.equal(r.action, 'simulated_merge_reversed'); assert.deepEqual(r.plan.patch, { company: 'Northstar Labs' }); assert.deepEqual(r.restored, x.records); assert.equal(r.after[0].owner, 'owner-1'); assert.equal(r.after[1].archived, true); assert.equal(JSON.stringify(x), original); assert.equal(mergePreview({ ...x, mode: 'simulate_undo_conflict' }).action, 'undo_conflict_hold'); assert.equal(mergePreview({ ...x, acknowledged: false }).action, 'review_required'); });
test('merge candidates reject same-domain false positives and conflicting consent, ownership or names', () => { for (const [key, value, reason] of [['email', 'other@example.test', 'email_identity_differs'], ['owner', 'other', 'owner_conflict'], ['consent', false, 'consent_conflict'], ['tenant', 'foreign', 'cross_tenant'], ['name', 'Different Person', 'name_identity_conflict']]) {
    const x = fixture('F07');
    x.records[1][key] = value;
    const r = mergePreview(x);
    assert.equal(r.action, 'stewardship_hold');
    assert.ok(r.reasons.includes(reason));
    assert.ok(!r.after);
} const x = fixture('F07'); x.records[1].consent = 'true'; assert.throws(() => mergePreview(x), /boolean/); });
test('consent uses event time and known time, revocation wins ties, repeats dedupe, expiry and purpose hold', () => { const x = fixture('F09'); assert.equal(journey(x).reason, 'revoked'); x.events = x.events.slice(0, 1); assert.equal(journey(x).action, 'eligible_transition_preview'); assert.equal(journey({ ...x, purpose: 'service' }).reason, 'no_applicable_consent'); assert.equal(journey({ ...x, asOf: '2026-11-01T12:00:00.000Z' }).reason, 'expired'); x.events.push(structuredClone(x.events[0])); assert.equal(journey(x).uniqueEvents, 1); const bad = fixture('F09'); bad.events[1].occurredAt = bad.events[0].occurredAt; assert.equal(journey(bad).reason, 'revoked'); bad.events[1].knownAt = '2026-10-06T12:00:00.000Z'; assert.equal(journey(bad).reason, 'active_scoped_grant'); x.events[1].expiresAt = '2026-12-01T12:00:00.000Z'; assert.throws(() => journey(x), /Conflicting duplicate/); });
test('usage ledger uses exact cents, duplicate suppression and next-period credits with balanced journal', () => { const x = fixture('F10'), r = usageLedger(x); assert.equal(r.amountCents, 2500); assert.equal(r.nextInvoiceAdjustmentCents, -250); assert.equal(r.balanced, true); assert.equal(r.journal[0].debitCents, 2500); x.events.push(structuredClone(x.events[0])); assert.equal(usageLedger(x).amountCents, 2500); x.events.at(-1).units = 101; assert.throws(() => usageLedger(x), /Conflicting/); });
test('ledger rejects fractional or boolean metering, excess credits, boundary-period leakage and bad currency', () => { for (const units of [true, 1.5, 0]) {
    const x = fixture('F10');
    x.events[0].units = units;
    assert.throws(() => usageLedger(x));
} const x = fixture('F10'); x.events[1].units = -101; assert.throws(() => usageLedger(x), /exceeds/); const boundary = fixture('F10'); boundary.events[0].occurredAt = boundary.periodEnd; boundary.events[0].postedAt = boundary.periodEnd; assert.throws(() => usageLedger(boundary), /half-open/); assert.throws(() => usageLedger({ ...fixture('F10'), currency: 'EUR' })); });
test('scheduling distinguishes repeated wall times by offsets and ignores cancelled appointments', () => { const r = scheduleBoard(fixture('F11')); assert.equal(r.decisions[0].action, 'scheduling_hold'); assert.deepEqual(r.decisions[0].conflicts, ['early-booking']); assert.equal(r.decisions[1].action, 'eligible_window_preview'); assert.equal(r.decisions[0].startUTC, '2026-11-01T05:15:00.000Z'); assert.equal(r.decisions[1].startUTC, '2026-11-01T06:15:00.000Z'); const x = fixture('F11'); x.slots[1].accessConfirmed = false; assert.equal(scheduleBoard(x).action, 'all_windows_held'); });
test('timestamps reject impossible calendars, missing offsets and malformed offset ranges', () => { for (const value of ['2026-02-30T12:00:00Z', '2026-10-01T12:00:00', '2026-10-01T12:00:00+15:00', '2026-10-01T24:00:00Z'])
    assert.throws(() => instant(value)); });
test('owned-code regression challenge exposes a broken candidate and validates corrected behavior', () => { const bad = reconstructionChallenge({ candidate: 'baseline' }), good = reconstructionChallenge({ candidate: 'reconstructed' }); assert.ok(bad.passed < bad.total); assert.equal(good.passed, 10); assert.equal(good.cases.find(c => c.id === 'reserved').actual.value, 14); assert.equal(good.cases.find(c => c.id === 'ceil').actual.value, 8); assert.equal(good.cases.find(c => c.id === 'zero-pack').actual.kind, 'rejected'); assert.throws(() => reconstructionChallenge({ candidate: 'arbitrary code' })); });
