import {humanProjects,runHuman} from './human-projects.mjs';
const escape=s=>String(s).replace(/[&<>"']/g,c=>({'&':'&amp;','<':'&lt;','>':'&gt;','"':'&quot;',"'":'&#39;'}[c]));
export function humanResultHTML(output){const max=Math.max(1,...output.rows.map(r=>r.value));return `<p class="human-result-summary">${escape(output.summary)}</p><figure><figcaption>Calculated from your inputs · ${escape(output.unit)}</figcaption>${output.rows.map(r=>`<div class="human-bar"><span>${escape(r.label)}</span><meter min="0" max="${max}" value="${r.value}">${r.value}</meter><strong>${escape(r.value)}</strong></div>`).join('')}</figure><details><summary>How the result is represented</summary><pre>${escape(JSON.stringify(output,null,2))}</pre></details>`;}
export function mountHumanStudio(document){
 const $=id=>document.getElementById(id);let selected=humanProjects[0],current=null;
 const root=$('humanStudio');if(!root)return;
 root.innerHTML=`<div class="human-heading"><span class="eyebrow">Life, curiosity and connection</span><h1>For the days<br><em>between deadlines.</em></h1><p>Twenty small tools for the things that make a life: a shared meal, a gentler trip, a book, a neighbour, a question worth exploring.</p><p class="meta">Working local prototypes · invented example data · nothing you enter is saved or sent</p></div><div class="personal-projects"><article><span class="eyebrow">PORT / OS</span><h2>Careful decisions behind real work.</h2><p>A private operating-system prototype that prepares, checks and routes work for human review. Explore its public engineering example; private operating records stay outside this gallery.</p><button id="humanPort">Explore the public PORT / OS example ↗</button></article><article><span class="eyebrow">PaceAtlas AI</span><h2>A trip shaped around the traveller.</h2><p>Your travel app is identified by name. Its repository was not found among the accessible GitHub repositories. Source verification and the original-app demo remain pending.</p><p class="meta">The three travel tools below are new independent prototypes, not claimed features of PaceAtlas AI.</p></article></div><div class="human-workspace"><aside class="human-index"><label for="humanFilter">Find your kind of project</label><select id="humanFilter"><option>All 20 projects</option>${[...new Set(humanProjects.map(p=>p.category))].map(c=>`<option>${escape(c)}</option>`).join('')}</select><div id="humanList"></div></aside><section id="humanDetail" aria-live="off"></section></div>`;
 function drawList(){const filter=$('humanFilter').value;$('humanList').innerHTML=humanProjects.filter(p=>filter==='All 20 projects'||p.category===filter).map(p=>`<button data-human-id="${p.id}" aria-pressed="${p.id===selected.id}"><span>${escape(p.category)}</span><strong>${escape(p.title)}</strong><small>${escape(p.tagline)}</small></button>`).join('');for(const b of $('humanList').querySelectorAll('button'))b.onclick=()=>{selected=humanProjects.find(p=>p.id===b.dataset.humanId);drawDetail();drawList();};}
 function calculate(){try{const input={};for(const f of selected.fields){const text=$('human-'+f.key).value.trim();if(!text)throw Error('Complete every field before calculating.');if(f.type==='list'){const tokens=text.split(',').map(s=>s.trim());if(tokens.some(v=>!v))throw Error('Each comma-separated item needs a number.');input[f.key]=tokens.map(Number);}else input[f.key]=Number(text);}const output=runHuman(selected.id,input);current={project:selected.id,input,output,dataOrigin:'User-editable local example',createdAt:new Date().toISOString()};$('humanOutput').innerHTML=humanResultHTML(output);$('humanError').textContent='';$('humanExport').disabled=false;}catch(error){current=null;$('humanOutput').innerHTML='';$('humanError').textContent=error.message;$('humanExport').disabled=true;}}
 function drawDetail(){current=null;$('humanDetail').innerHTML=`<div class="eyebrow">${escape(selected.id)} / ${escape(selected.category)}</div><h2>${escape(selected.title)}</h2><p class="human-tagline">${escape(selected.tagline)}</p><p>${escape(selected.story)}</p><div class="human-demo"><form id="humanForm"><h3>Make the example yours</h3>${selected.fields.map(f=>`<label for="human-${f.key}">${escape(f.label)}${f.type==='list'?'<small>Separate values with commas.</small>':''}<input id="human-${f.key}" ${f.type==='number'?'type="number" min="0" step="any"':'type="text"'} value="${escape(Array.isArray(f.value)?f.value.join(', '):f.value)}" required></label>`).join('')}<div class="actions"><button type="submit" class="primary">Explore the result</button><button type="button" id="humanReset">Reset example</button></div><p id="humanError" role="alert"></p></form><div><div id="humanOutput"></div><button id="humanExport" disabled>Save this example as JSON</button></div></div><p class="meta">${escape(selected.scope)} The result explains a bounded calculation; it does not make decisions for you.</p>`;$('humanForm').onsubmit=e=>{e.preventDefault();calculate();};$('humanReset').onclick=drawDetail;$('humanExport').onclick=()=>{if(!current)return;const view=document.defaultView,url=view.URL.createObjectURL(new view.Blob([JSON.stringify(current,null,2)],{type:'application/json'}));const a=document.createElement('a');a.href=url;a.download=selected.id+'-example.json';a.click();view.setTimeout(()=>view.URL.revokeObjectURL(url),1000);};calculate();}
 $('humanFilter').onchange=drawList;$('humanPort').onclick=()=>{root.hidden=true;document.dispatchEvent(new document.defaultView.Event('open-port-example'));};
 drawList();drawDetail();return {calculate};
}
if(typeof document!=='undefined')mountHumanStudio(document);
