import test from 'node:test';import assert from 'node:assert/strict';
import {JSDOM} from 'jsdom';import {humanProjects,runHuman} from './human-projects.mjs';import {mountHumanStudio} from './human-studio.mjs';
const expected={
 'LIFE-01':r=>assert.equal(r.rows.at(-1).value,4),'LIFE-02':r=>assert.deepEqual(r.rows.map(r=>r.value),[334,334,333]),'LIFE-03':r=>assert.deepEqual(r.rows.map(r=>r.value),[2,2]),
 'TRIP-01':r=>assert.equal(r.rows.at(-1).value,35),'TRIP-02':r=>assert.equal(r.rows[0].value,7.3),'TRIP-03':r=>assert.deepEqual(r.rows.map(r=>r.value),[30,22,35]),
 'LIFE-04':r=>assert.equal(r.details.overlap,2),'LIFE-05':r=>assert.equal(r.details.days,16),'LIFE-06':r=>assert.equal(r.details.remaining,45),'CARE-01':r=>assert.equal(r.details.suggested,1),
 'CARE-02':r=>assert.equal(r.details.gap,2),'LIFE-07':r=>assert.equal(r.details.difference,80),'DATA-01':r=>assert.equal(r.details.mean,470),'DATA-02':r=>assert.equal(r.details.cost,2.8),
 'CARE-03':r=>assert.equal(r.details.published,false),'CARE-04':r=>assert.deepEqual(r.rows.map(r=>r.value),[2,2,1]),'DATA-03':r=>assert.equal(r.details.median,25),
 'DATA-04':r=>assert.equal(r.details.mean,4),'DATA-05':r=>assert.equal(r.details.difference,6.67),'DATA-06':r=>assert.equal(r.details.medianGap,15.5)
};
for(const p of humanProjects)test(p.id+' computes its independently expected result and rejects invalid input',()=>{expected[p.id](runHuman(p.id,structuredClone(p.fixture)));const bad=structuredClone(p.fixture);bad[p.fields[0].key]=p.fields[0].type==='list'?[]:-1;assert.throws(()=>runHuman(p.id,bad));});
test('human tools preserve missingness, limits and no-action boundaries',()=>{assert.equal(runHuman('DATA-04',{scores:[0,0]}).details.mean,null);assert.equal(runHuman('CARE-01',{loads:[3,4],capacity:3}).details.suggested,null);assert.equal(runHuman('TRIP-01',{walks:[100],rest:20,available:60}).details.overBy,60);assert.throws(()=>runHuman('TRIP-03',{times:[1],stairs:[1,2],penalty:1}));assert.throws(()=>runHuman('CARE-04',{flags:[3]}));assert.throws(()=>runHuman('LIFE-02',{cents:1.2,people:2}));});
test('all 20 human interfaces calculate, recover from bad inputs and filter',()=>{const dom=new JSDOM('<main id="humanStudio"></main>',{url:'http://127.0.0.1:5680'});const d=dom.window.document;mountHumanStudio(d);assert.equal(d.querySelectorAll('[data-human-id]').length,20);for(const p of humanProjects){d.querySelector(`[data-human-id="${p.id}"]`).click();assert.ok(d.querySelectorAll('#humanOutput meter').length>0,p.id);assert.equal(d.getElementById('humanError').textContent,'');}const field=d.querySelector('#humanForm input');field.value='1,,2';d.getElementById('humanForm').dispatchEvent(new dom.window.Event('submit',{cancelable:true}));assert.match(d.getElementById('humanError').textContent,/number/);assert.equal(d.getElementById('humanExport').disabled,true);d.getElementById('humanReset').click();assert.equal(d.getElementById('humanError').textContent,'');d.getElementById('humanFilter').value='Data stories';d.getElementById('humanFilter').dispatchEvent(new dom.window.Event('change'));assert.equal(d.querySelectorAll('[data-human-id]').length,6);dom.window.close();});
