const host=document.getElementById('build-review');
const esc=x=>String(x).replaceAll('&','&amp;').replaceAll('<','&lt;').replaceAll('>','&gt;').replaceAll('"','&quot;');
if(host)fetch('/build-review.json',{cache:'no-store'}).then(r=>{if(!r.ok)throw Error('No recorded review is available.');return r.json();}).then(r=>{
 host.innerHTML=`<h2>Evidence you can inspect</h2><p>Local checks recorded ${esc(r.reviewedAt)}. ${r.passed?'These three recorded command checks passed; this is not the governor decision.':'This review contains failing checks.'}</p><div class="reference-grid">${r.checks.map(c=>`<article><h3>${esc(c.name)}</h3><p>${c.passed?'Passed':'Needs attention'}${c.testCount?' · '+c.testCount+' tests':''}</p><details><summary>Read command output</summary><pre>${esc(c.output)}</pre></details></article>`).join('')}</div><p>n8n: ${r.n8n.projects} demonstrations · ${r.n8n.passed?'passed':'needs attention'} · replay ${r.n8n.replayPassed?'passed':'failed'}. Separately recorded ${esc(r.n8n.recordedAt)}.</p><details><summary>Timing and scope</summary><p>${esc(r.benchmark.scope)}</p><ul>${r.benchmark.phases.map(p=>`<li>Concurrency ${p.concurrency}: ${p.requests} requests, ${p.errors} errors, p95 ${p.p95Ms.toFixed(2)} ms.</li>`).join('')}</ul><p>Slowest recorded n8n example: ${esc(r.n8n.slowest[0]?.id??'unavailable')} (${esc(r.n8n.slowest[0]?.engineDurationMs??'unavailable')} ms). Timing includes that recorded engine run; it is not an SLA.</p><p>${esc(r.n8n.scope)}</p></details><p class="scope">${esc(r.scope)}</p><a href="/build-review.json" target="_blank">Open complete review and source hashes ↗</a>`;
}).catch(()=>{host.textContent='Recorded verification is unavailable. Run node demo-lab/review-portfolio.mjs locally to generate it.';});

const governorHost=document.getElementById('governor');
if(governorHost)fetch('/api/governance',{cache:'no-store'}).then(r=>{if(!r.ok)throw Error();return r.json();}).then(r=>{
 const approved=r.effectiveDecision==='approved-local-checks';
 governorHost.innerHTML=`<p class="eyebrow">Scope → Specialists → Cross-check → Governor</p><h2>${approved?'Local checks approved':r.effectiveDecision==='needs-work'?'Changes required':'Incomplete evidence'}</h2><p>Three automated specialists inspect different parts of this local build. The governor checks their results and source identity. Independent AI critique is performed separately in the Codex task.</p>${r.stale?'<p class="scope">The recorded review does not match the current source, or no completed review exists. Rerun the governor.</p>':''}<ul>${r.governor.reasons.map(reason=>`<li>${esc(reason)}</li>`).join('')}</ul><div class="reference-grid">${r.results.map(s=>`<article><h3>${esc(s.role)}</h3><p>${esc(s.status)} · ${s.checks} checks · exit ${esc(s.exitCode)}</p><details><summary>Inspect evidence</summary><pre>${esc(s.output)}</pre></details></article>`).join('')}</div><p class="scope">Run ${esc(r.runId??'unavailable')} · ${esc(r.completedAt??'not completed')}. Approval covers the automated local checks, not production readiness or permission to publish.</p><p>Repeat locally: <code>npm run govern</code> inside <code>Portfolio/demo-lab</code>.</p><a href="/api/governance" target="_blank">Inspect governor report and snapshot ↗</a>`;
}).catch(()=>{governorHost.textContent='Governor evidence unavailable. Run npm run govern in Portfolio/demo-lab.';});
