import {extendedProjects} from './workbench-extended.mjs';
import repairEvidence from './repair-evidence.mjs';
// Deterministic infrastructure for inspecting AI outputs and actions. No model calls.
const object=x=>{if(!x||typeof x!=='object'||Array.isArray(x))throw Error('Expected a JSON object.');};
const list=(x,label)=>{if(!Array.isArray(x)||!x.length||x.length>100)throw Error(label+' needs 1–100 records.');};
const str=(x,label)=>{if(typeof x!=='string'||!x.trim()||x.length>10000)throw Error(label+' must be nonempty text (maximum 10,000 characters).');};
const num=(x,label)=>{if(typeof x!=='number'||!Number.isFinite(x)||x<0||x>1e9)throw Error(label+' must be a finite nonnegative number.');};
function unique(rows){const ids=new Set();for(const r of rows){object(r);str(r.id,'ID');if(ids.has(r.id))throw Error('Duplicate ID: '+r.id);ids.add(r.id);}}
export function verifyClaims(input){
 object(input);str(input.tenant,'Tenant');list(input.sources,'Sources');list(input.claims,'Claims');unique(input.sources);unique(input.claims);
 for(const s of input.sources){str(s.tenant,'Source tenant');str(s.text,'Source text');if(typeof s.approved!=='boolean')throw Error('Source approved must be boolean.');}
 const decisions=input.claims.map(c=>{str(c.source,'Source ID');str(c.quote,'Quote');str(c.text,'Claim text');const s=input.sources.find(s=>s.id===c.source);const reasons=[];
 if(!s)reasons.push('Source does not exist');else{if(s.tenant!==input.tenant)reasons.push('Source belongs to another tenant');if(!s.approved)reasons.push('Source is not approved');if(!s.text.includes(c.quote))reasons.push('Quote is not an exact source excerpt');}
 // Exact extraction only: do not pretend a string check proves entailment of a paraphrase.
 if(c.text!==c.quote)reasons.push('Claim differs from the quote: semantic review required');
 return {id:c.id,status:reasons.length?'review':'verified-excerpt',reasons,source:c.source,quote:reasons.length?null:c.quote};});
 return {kind:'claims',summary:`${decisions.filter(x=>x.status==='verified-excerpt').length} of ${decisions.length} claims are exact approved excerpts.`,decisions,metrics:[{label:'Verified excerpts',value:decisions.filter(x=>x.status==='verified-excerpt').length},{label:'Needs review',value:decisions.filter(x=>x.status==='review').length}],scope:'Exact excerpt integrity only. Not semantic truth, source accuracy, authentication or general injection resistance.'};
}
export function replayActions(input){
 object(input);list(input.actions,'Actions');unique(input.actions);let ledger=new Map(),balance=0;
 const decisions=input.actions.map(a=>{str(a.key,'Idempotency key');str(a.tool,'Tool');num(a.amount,'Amount');if(!Number.isInteger(a.amount))throw Error('Amount must use whole demo units.');if(typeof a.approved!=='boolean')throw Error('Approval must be boolean.');if(!['success','timeout-before','timeout-after'].includes(a.outcome))throw Error('Unknown simulated outcome.');
 let status,reason;const previous=ledger.get(a.key);
 if(a.tool!=='reserve-demo-units'){status='blocked';reason='Tool is outside the allowlist';}
 else if(!a.approved){status='blocked';reason='Human approval is missing';}
 else if(previous){if(previous.amount!==a.amount){status='conflict';reason='Same key with different request payload';}else if(previous.state==='uncertain'){status='reconcile';reason='Previous write may have committed; retry held';}else{status='duplicate';reason='Completed request reused; no second write';}}
 else if(a.outcome==='timeout-before'){status='retryable';reason='Simulation confirms no write occurred';}
 else{balance+=a.amount;const uncertain=a.outcome==='timeout-after';ledger.set(a.key,{amount:a.amount,state:uncertain?'uncertain':'complete'});status=uncertain?'uncertain':'completed';reason=uncertain?'Simulator committed, but acknowledgement was lost':'Approved local state change recorded';}
 return {id:a.id,status,reason,key:a.key,simulatorTotal:balance};});
 return {kind:'actions',summary:`${balance} demo units recorded; ${ledger.size} unique writes.`,decisions,ledger:[...ledger].map(([key,value])=>({key,...value})),metrics:[{label:'Unique writes',value:ledger.size},{label:'Held or blocked steps',value:decisions.filter(d=>!['completed','retryable'].includes(d.status)).length}],scope:'In-memory simulation resets per run. Approval is a fixture field, not identity verification. No external tools, payments or durable database.'};
}
export function compareEvaluations(input){
 object(input);list(input.cases,'Cases');unique(input.cases);num(input.budget,'Per-case latency budget');
 for(const c of input.cases){str(c.expected,'Expected answer');str(c.baseline,'Baseline answer');str(c.candidate,'Candidate answer');num(c.baselineMs,'Baseline latency');num(c.candidateMs,'Candidate latency');}
 const decisions=input.cases.map(c=>({id:c.id,baselinePass:c.baseline===c.expected,candidatePass:c.candidate===c.expected,baselineMs:c.baselineMs,candidateMs:c.candidateMs,overBudget:c.candidateMs>input.budget}));
 const baseline=decisions.filter(c=>c.baselinePass).length,candidate=decisions.filter(c=>c.candidatePass).length,regressions=decisions.filter(c=>c.baselinePass&&!c.candidatePass).map(c=>c.id),fixes=decisions.filter(c=>!c.baselinePass&&c.candidatePass).map(c=>c.id);
 const sorted=decisions.map(c=>c.candidateMs).sort((a,b)=>a-b),p95=sorted[Math.ceil(sorted.length*.95)-1];
 return {kind:'evals',summary:regressions.length?'Hold: the candidate regresses on previously passing cases.':candidate===decisions.length&&!decisions.some(c=>c.overBudget)?'Candidate meets this fixture’s exact-match and latency gates.':'Hold: candidate has failures or exceeds the entered latency budget.',decisions,regressions,fixes,p95,metrics:[{label:'Baseline exact matches',value:baseline},{label:'Candidate exact matches',value:candidate}],scope:'Grades supplied outputs with exact equality. Latencies are fixture values, not live measurements. No independent model benchmark or statistical significance claim.'};
}
export const workbenchProjects=[
 {id:'ENG-01',name:'ClaimProof',category:'Evidence engineering',headline:'A confident sentence needs a source.',description:'An analyst prepares a product brief. One sentence is a faithful excerpt, one changes a quantity, and another cites a different team’s document. Inspect exactly which claims can be shown and which need review.',method:'Validate records → check tenant and approval → match the quote → flag changed claims',run:verifyClaims,fixture:{tenant:'bakery',sources:[{id:'spec',tenant:'bakery',approved:true,text:'Each box contains 12 cookies. Store in a cool dry place.'},{id:'other',tenant:'other-team',approved:true,text:'Wholesale minimum is 40 boxes.'}],claims:[{id:'c1',source:'spec',quote:'Each box contains 12 cookies.',text:'Each box contains 12 cookies.'},{id:'c2',source:'spec',quote:'Each box contains 12 cookies.',text:'Each box contains 24 cookies.'},{id:'c3',source:'other',quote:'Wholesale minimum is 40 boxes.',text:'Wholesale minimum is 40 boxes.'}]},questions:['How do you distinguish a citation from support for a claim?','What happens when a source exists but is not authorized?'],limit:'A trustworthy excerpt is not proof the underlying document is true.'},
 {id:'ENG-02',name:'Action Ledger',category:'Tool execution controls',headline:'A timeout is not permission to try again.',description:'A planning assistant requests a reservation of demo units. The write succeeds but its acknowledgement disappears. Replay the same request and see why the controller holds it for reconciliation instead of writing twice.',method:'Allowlist → approval → request identity → simulated write → replay decision',run:replayActions,fixture:{actions:[{id:'a1',key:'order-1',tool:'reserve-demo-units',amount:12,approved:true,outcome:'timeout-after'},{id:'a2',key:'order-1',tool:'reserve-demo-units',amount:12,approved:true,outcome:'success'},{id:'a3',key:'order-2',tool:'reserve-demo-units',amount:8,approved:false,outcome:'success'}]},questions:['What if the write succeeded but the response was lost?','Which state must persist before this could run in production?'],limit:'The ledger demonstrates control logic in memory; production needs durable state and authenticated approvals.'},
 {id:'ENG-03',name:'Eval Observatory',category:'Regression evaluation',headline:'An average can hide the failure that matters.',description:'A candidate assistant fixes one answer but breaks another that previously passed. Compare case-by-case outcomes and latency gates before deciding whether the change should advance.',method:'Validate paired cases → grade exact outputs → identify fixes and regressions → apply latency gate',run:compareEvaluations,fixture:{budget:500,cases:[{id:'returns',expected:'review',baseline:'review',candidate:'approve',baselineMs:180,candidateMs:140},{id:'inventory',expected:'hold',baseline:'approve',candidate:'hold',baselineMs:200,candidateMs:260},{id:'content',expected:'reject',baseline:'reject',candidate:'reject',baselineMs:300,candidateMs:650}]},questions:['Did the candidate fix something without breaking a known behavior?','Are the latency figures observed or supplied?'],limit:'Exact-match grading is appropriate for these labels, not arbitrary natural-language quality.'}
];

workbenchProjects.push(...extendedProjects, {
 id:'ENG-09',name:'Repair Studio',category:'Codex-assisted development',headline:'Show the failing test before the fix.',description:'A shop receives the same delivery event twice. The original function deducts stock twice. Inspect a Codex-assisted candidate that remembers event IDs, rejects conflicting retries and validates quantities. Compare the actual recorded test runs before recording your review decision.',method:'Reproduce duplicate event → inspect original and candidate → review actual tests → record decision',fixture:{reviewDecision:'defer'},questions:['Do the tests prove the business requirement?','What would change if events arrived across separate processes?'],limit:'Fixed source example and recorded test evidence. Not a Codex SDK product or a durable production inventory system.',run(x){if(!['accept','defer','reject'].includes(x.reviewDecision))throw Error('Review decision must be accept, defer or reject.');return {summary:repairEvidence.verified?'Baseline failed; candidate passed all five checks. Review remains a human decision.':'Recorded repair checks need attention.',decisions:repairEvidence.runs.map(r=>({id:r.variant,status:r.exitCode===0?'tests passed':'tests failed',reason:r.output})),metrics:repairEvidence.runs.map(r=>({label:r.variant+' measured ms',value:r.elapsedMs})),evidence:repairEvidence,reviewDecision:x.reviewDecision,scope:repairEvidence.scope};}
});
