import {workbenchProjects} from './workbench-core.mjs';
import {scenarios,scenarioInput,engineeringNotes,traceRows} from './workbench-story.mjs';
export function mountWorkbench(d){
 const $=id=>d.getElementById(id),esc=x=>String(x).replaceAll('&','&amp;').replaceAll('<','&lt;').replaceAll('>','&gt;').replaceAll('"','&quot;');let selected=workbenchProjects[0],last=null;
 function clear(){last=null;$('export').disabled=true;$('error').textContent='';$('state').textContent='Ready';$('result').innerHTML='<p class="empty">Run the example to reveal its decisions.</p>';}
 function controls(){if($('project-source'))$('project-source').href=['ENG-04','ENG-05','ENG-06','ENG-07','ENG-08'].includes(selected.id)?'/workbench-extended.mjs':selected.id==='ENG-09'?'/repair-evidence.mjs':'/workbench-core.mjs';const host=$('guided');if(!host)return;host.innerHTML='';let x;try{x=JSON.parse($('input').value);}catch{return;}
 if(scenarios[selected.id])host.innerHTML='<label>Choose a situation<select id="scenario"><option value="" disabled selected>Current input / bundled example</option>'+scenarios[selected.id].map(([key,label])=>`<option value="${key}">${esc(label)}</option>`).join('')+'</select></label><p class="scope">Choosing a situation replaces the input. Run it to see the new outcome.</p>';
 if(selected.id==='ENG-04'&&Array.isArray(x?.cases)&&x.cases.every(c=>c&&typeof c==='object'))host.innerHTML='<h3>Review the answers</h3>'+x.cases.map((c,i)=>`<label>${esc(c.id)}: ${esc(c.output)}<select data-review="${i}" aria-label="Review ${esc(c.id)}"><option value="" ${c.label===null?'selected':''}>Unreviewed</option><option value="accept" ${c.label==='accept'?'selected':''}>Accept</option><option value="reject" ${c.label==='reject'?'selected':''}>Reject</option></select></label><label>Reason for ${esc(c.id)}<input data-reason="${i}" value="${esc(c.reason??'')}"></label>`).join('');
 if(selected.id==='ENG-05'&&Array.isArray(x?.fields)&&x.fields.every(f=>f&&typeof f==='object'))host.innerHTML='<h3>Correct the catalog draft</h3>'+x.fields.map((f,i)=>`<label>${esc(f.id)} · source: ${esc(f.quote)}<input data-field="${i}" value="${esc(f.value)}"></label><label><input type="checkbox" data-approve="${i}" ${f.approved?'checked':''}> I reviewed ${esc(f.id)}</label>`).join('');
 if(selected.id==='ENG-09')host.innerHTML='<label>Review decision<select id="repair-review"><option value="defer">Defer</option><option value="accept">Accept for this example</option><option value="reject">Reject</option></select></label>';
 if($('scenario'))$('scenario').onchange=()=>{if(!$('scenario').value)return;$('input').value=JSON.stringify(scenarioInput(selected.id,$('scenario').value,selected.fixture),null,2);clear();};
 const sync=()=>{$('input').value=JSON.stringify(x,null,2);clear();};
 for(const el of host.querySelectorAll('[data-review]'))el.onchange=()=>{x.cases[+el.dataset.review].label=el.value||null;sync();};
 for(const el of host.querySelectorAll('[data-reason]'))el.oninput=()=>{x.cases[+el.dataset.reason].reason=el.value;sync();};
 for(const el of host.querySelectorAll('[data-field]'))el.oninput=()=>{const f=x.fields[+el.dataset.field];f.value=f.id==='packCount'?Number(el.value):el.value;f.approved=false;const box=host.querySelector(`[data-approve="${el.dataset.field}"]`);if(box)box.checked=false;sync();};
 for(const el of host.querySelectorAll('[data-approve]'))el.onchange=()=>{x.fields[+el.dataset.approve].approved=el.checked;sync();};
 if($('repair-review')&&x){$('repair-review').value=x.reviewDecision;$('repair-review').onchange=()=>{x.reviewDecision=$('repair-review').value;sync();};}
 }
 function select(p){selected=p;if(d.defaultView.location.hash!=="#"+p.id)d.defaultView.history.pushState(null,"","#"+p.id);clear();$('category').textContent=p.category;$('headline').textContent=p.headline;$('description').textContent=p.description;$('limit').textContent=p.limit;$('method').innerHTML=p.method.split(' → ').map(s=>'<li>'+esc(s)+'</li>').join('');$('questions').innerHTML=p.questions.map(s=>'<li>'+esc(s)+'</li>').join('');$('input').value=JSON.stringify(p.fixture,null,2);for(const b of $('projects').querySelectorAll('button'))b.setAttribute('aria-pressed',String(b.dataset.project===p.id));controls();engineeringPanel();}
 $('projects').innerHTML=workbenchProjects.map(p=>`<button data-project="${p.id}"><small>${p.id} / ${esc(p.category)}</small><strong>${esc(p.name)}</strong></button>`).join('');
 for(const b of $('projects').querySelectorAll('button'))b.onclick=()=>{select(workbenchProjects.find(p=>p.id===b.dataset.project));d.defaultView.location.hash=b.dataset.project;if($('project-source'))$('project-source').href=['ENG-04','ENG-05','ENG-06','ENG-07','ENG-08'].includes(selected.id)?'/workbench-extended.mjs':selected.id==='ENG-09'?'/repair-evidence.mjs':'/workbench-core.mjs';};
 if($('import-evidence'))$('import-evidence').onchange=async()=>{clear();try{const file=$('import-evidence').files[0];if(!file)return;if(file.size>100000)throw Error('Import exceeds 100 KB.');const saved=JSON.parse(await file.text()),p=workbenchProjects.find(p=>p.id===saved.project);if(!p)throw Error('Unknown project in export.');p.run(saved.input);select(p);$('input').value=JSON.stringify(saved.input,null,2);controls();$('state').textContent='Input restored; rerun to verify';}catch(e){$('error').textContent=e.message;}finally{$('import-evidence').value='';}};
 d.defaultView.addEventListener('hashchange',()=>{const p=workbenchProjects.find(p=>p.id===d.defaultView.location.hash.slice(1));if(p&&p.id!==selected.id)select(p);});
 $('input').oninput=()=>{clear();controls();};$('reset').onclick=()=>select(selected);
 function engineeringPanel(){
  let host=$('engineering-notes');if(!host){host=d.createElement('div');host.id='engineering-notes';$('project-source').after(host);}
  const n=engineeringNotes[selected.id];
  host.innerHTML=n?`<details class="engineering-notes"><summary>Engineering choices &amp; reproduce locally</summary><h3>Start with ${esc(n.fn)}</h3><p>${esc(n.choice)}</p>${selected.id==='ENG-09'?'<h3>Read the fix in three steps</h3><ol><li>The acceptance case starts with 20 units and repeats event a with quantity 3. It expects 17 units remaining.</li><li>receive stores each event ID with its quantity. An identical repeat is skipped; a changed quantity for the same ID throws a conflict.</li><li>The map exists only during this call. Separate requests need shared durable storage.</li></ol><p>Run the example, then expand candidate.mjs below to inspect the recorded implementation beside the actual test output.</p>':''}<h3>Failure boundary</h3><p>${esc(n.failure)}</p><p>${esc(n.next)}</p><h3>Reproduce this example</h3><ol><li>Choose a situation or edit the input, then run it.</li><li>Export the input and result. Restore that JSON to replay the same input; imported results are ignored.</li><li>From the Portfolio folder, run the command below to check the implementation.</li></ol><pre>${selected.id==='ENG-09'?'node demo-lab/verify-repair.mjs':'node --test demo-lab/workbench.test.mjs demo-lab/workbench-extended.test.mjs demo-lab/workbench-story.test.mjs'}</pre><p>${selected.id==='ENG-09'?'This command regenerates repair-evidence.mjs. Reload the page to inspect its recorded timestamp, exact sources, hashes and measured test durations.':'The command tests the implementation with fixed regression cases. The browser runs your edited input; exporting preserves that input and its local result.'}</p></details>`:'';
 }
 function decisionTrace(input,result){
  const rows=traceRows(selected.id,input,result);if(!rows.length)return '';
  return `<section class="decision-trace"><h3>Follow the actual decisions</h3><p class="scope">${selected.id==='ENG-02'?'Sequential steps in this in-memory simulation.':'Computed from the input in this run.'} These are rule outcomes, not model reasoning.</p>${rows.map(r=>`<article class="decision"><h4>${esc(r.id)} <span>${esc(r.status)}</span></h4><ol><li><b>Input</b><p>${esc(r.input)}</p></li><li><b>Check</b><p>${esc(r.rule)}</p></li><li><b>Result</b><p>${esc(r.output)}</p></li></ol></article>`).join('')}${selected.id==='ENG-05'?`<h4>Catalog draft</h4><pre>${esc(result.catalog?JSON.stringify(result.catalog,null,2):'No catalog released. Resolve every required field before approval.')}</pre>`:''}</section>`;
 }
 function curve(rows){const max=Math.max(.001,...rows.flatMap(r=>[r.train,r.test])),points=key=>rows.map((r,i)=>`${40+i*420/(rows.length-1)},${170-r[key]/max*145}`).join(' ');return `<figure class="loss-chart"><figcaption>Measured loss · green training / orange held-out</figcaption><svg viewBox="0 0 500 200" role="img" aria-label="Training and held-out loss over update steps"><path d="M40 20V170H460" fill="none" stroke="#9aa"/><polyline points="${points('train')}" fill="none" stroke="#126d63" stroke-width="3"/><polyline points="${points('test')}" fill="none" stroke="#b85d27" stroke-dasharray="5 4" stroke-width="3"/><text x="5" y="20">${max.toFixed(2)}</text><text x="20" y="173">0</text><text x="40" y="193">Step 0</text><text x="385" y="193">Step ${rows.at(-1).step}</text></svg><details><summary>Loss data table</summary><table><thead><tr><th>Step</th><th>Training</th><th>Held-out</th></tr></thead><tbody>${rows.map(r=>`<tr><td>${r.step}</td><td>${r.train.toFixed(5)}</td><td>${r.test.toFixed(5)}</td></tr>`).join('')}</tbody></table></details></figure>`;}
 $('run').onclick=()=>{clear();try{if($('input').value.length>100000)throw Error('Fixture exceeds 100 KB.');const input=JSON.parse($('input').value),result=selected.run(input);last={project:selected.id,created:new Date().toISOString(),input,result};$('state').textContent=selected.id==='ENG-09'?'Recorded test evidence':'Evaluated locally';$('export').disabled=false;const max=Math.max(1,...result.metrics.map(m=>m.value));$('result').innerHTML=`<p class="result-summary">${esc(result.summary)}</p><div class="bars">${result.metrics.map(m=>`<div class="bar"><span>${esc(m.label)}</span><meter min="0" max="${max}" value="${m.value}" aria-label="${esc(m.label)}">${m.value}</meter><b>${m.value}</b></div>`).join('')}</div>${decisionTrace(input,result)}${result.curve?curve(result.curve):''}${(traceRows(selected.id,input,result).length?[]:result.decisions).map(x=>`<div class="decision"><strong>${esc(x.id)} · ${esc(x.status??(x.candidatePass?'candidate pass':'candidate fail'))}</strong>${selected.id==='ENG-09'?`<details><summary>Actual test output</summary><pre>${esc(x.reason)}</pre></details>`:`<p>${esc(x.reason??x.reasons?.join('; ')??`Baseline: ${x.baselinePass?'pass':'fail'} · Candidate: ${x.candidatePass?'pass':'fail'} · ${x.candidateMs} ms (fixture)${x.overBudget?' · over budget':''}`)}</p>`}</div>`).join('')}${result.evidence?`<p>Recorded ${esc(result.evidence.created)} · ${esc(result.evidence.runtime)} · Review: ${esc(result.reviewDecision)}</p><div class="source-pair">${Object.entries(result.evidence.sources).map(([name,source])=>`<details><summary>${esc(name)}</summary><pre>${esc(source)}</pre><small>SHA-256: ${esc(result.evidence.sourceHashes[name])}</small></details>`).join('')}</div>`:''}<p class="scope">${esc(result.scope)}</p><details><summary>Complete result and trace</summary><pre>${esc(JSON.stringify(result,null,2))}</pre></details>`;}catch(e){$('state').textContent='Input needs attention';$('error').textContent=e.message;}};
 $('export').onclick=()=>{if(!last)return;const url=URL.createObjectURL(new Blob([JSON.stringify(last,null,2)],{type:'application/json'})),a=d.createElement('a');a.href=url;a.download=selected.id+'-evidence.json';a.click();setTimeout(()=>URL.revokeObjectURL(url),1000);};select(workbenchProjects.find(p=>p.id===d.defaultView.location.hash.slice(1))??selected);
}
if(typeof document!=='undefined')mountWorkbench(document);
